### ISSUE TITLE
Change ImageMagick requirement to apply when changing assets instead of on builds

### ISSUE THREAD

**Issue by brianjd** [stipsan/epic#579]
The favicon build step will actually fail if ImageMagick isn't installed.

**Comment by stipsan** [comment]
Thanks for the feedback!

I'm thinking maybe it's better to commit the icons generated by the favicon script to source control?
That way ImageMagick is no longer required as a build step on deploy, instead it's required only when you make graphical changes.

What do you think?

**Comment by brianjd** [comment]
@stipsan No worries, thanks for an awesome project!  It has definitely has schooled me on a few things.  

But yes, I totally agree.  Committing the generated icons is better.

**Comment by stipsan** [comment]
That's awesome to hear @brianjd 🎉 

I'll be sure to update the script 👍  I'll have time to work on epic again soon, I've been occupied with giving [ioredis-mock](https://github.com/stipsan/ioredis-mock) some much needed love 😮
